--------------------------------------------------------
--  DDL for Table AUTHORITIES
--------------------------------------------------------

  CREATE TABLE "KYPOTA"."AUTHORITIES" 
   (	"USERNAME" NVARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"AUTHORITY" NVARCHAR2(128) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table KYPARKS
--------------------------------------------------------

  CREATE TABLE "KYPOTA"."KYPARKS" 
   (	"ABBR" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PARK_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table LOGS
--------------------------------------------------------

  CREATE TABLE "KYPOTA"."LOGS" 
   (	"LOG_ID" NUMBER, 
	"ENTERED_ON" DATE, 
	"LOG_TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"FORMAT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CALLSIGN" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CLUB" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTEST" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"CAT_OPERATOR" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CAT_ASSISTED" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CAT_BAND" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CAT_MODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CAT_POWER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CAT_STATION" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CAT_TRANSMITTER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CLAIMED_SCORE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"OPERATORS" VARCHAR2(75 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(75 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"ZIP" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"GRID_LOC" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"SOAP_BOX" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"TIME_START" DATE, 
	"TIME_END" DATE, 
	"RAW_LOG" CLOB COLLATE "USING_NLS_COMP", 
	"SUBMITTED_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBMITTED_EMAIL" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"PARK_ABBR" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("RAW_LOG") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table QSOS
--------------------------------------------------------

  CREATE TABLE "KYPOTA"."QSOS" 
   (	"LOG_ID" NUMBER, 
	"QSO_ID" NUMBER, 
	"QSO_MODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"QSO_DATE" DATE, 
	"SNT_CALL" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"SNT_RST" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"SNT_EXCH" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"RCV_CALL" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"RCV_RST" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"RCV_EXCH" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"FREQ" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSMITTER_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DUP" NUMBER(1,0) DEFAULT 0, 
	"P2P" NUMBER(1,0) DEFAULT 0, 
	"BONUS_STN" NUMBER(1,0) DEFAULT 0, 
	"BAND" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_ANALYSED" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "KYPOTA"."USERS" 
   (	"USERNAME" NVARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"PASSWORD" NVARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"ENABLED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index AUTHORITIES_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYPOTA"."AUTHORITIES_UNIQUE" ON "KYPOTA"."AUTHORITIES" ("USERNAME", "AUTHORITY") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index KYPARKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYPOTA"."KYPARKS_PK" ON "KYPOTA"."KYPARKS" ("ABBR") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index LOGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYPOTA"."LOGS_PK" ON "KYPOTA"."LOGS" ("LOG_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index QSO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYPOTA"."QSO_PK" ON "KYPOTA"."QSOS" ("QSO_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0016363
--------------------------------------------------------

  CREATE UNIQUE INDEX "KYPOTA"."SYS_C0016363" ON "KYPOTA"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "KYPOTA"."AUTHORITIES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "KYPOTA"."AUTHORITIES" MODIFY ("AUTHORITY" NOT NULL ENABLE);
  ALTER TABLE "KYPOTA"."AUTHORITIES" ADD CONSTRAINT "AUTHORITIES_UNIQUE" UNIQUE ("USERNAME", "AUTHORITY")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KYPARKS
--------------------------------------------------------

  ALTER TABLE "KYPOTA"."KYPARKS" ADD CONSTRAINT "KYPARKS_PK" PRIMARY KEY ("ABBR")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOGS
--------------------------------------------------------

  ALTER TABLE "KYPOTA"."LOGS" MODIFY ("LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "KYPOTA"."LOGS" ADD CONSTRAINT "LOGS_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QSOS
--------------------------------------------------------

  ALTER TABLE "KYPOTA"."QSOS" ADD CONSTRAINT "QSO_PK" PRIMARY KEY ("QSO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "KYPOTA"."QSOS" MODIFY ("LOG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "KYPOTA"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "KYPOTA"."USERS" MODIFY ("ENABLED" NOT NULL ENABLE);
  ALTER TABLE "KYPOTA"."USERS" ADD CHECK (ENABLED IN ('Y','N') ) ENABLE;
  ALTER TABLE "KYPOTA"."USERS" ADD PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "KYPOTA"."AUTHORITIES" ADD CONSTRAINT "AUTHORITIES_FK1" FOREIGN KEY ("USERNAME")
	  REFERENCES "KYPOTA"."USERS" ("USERNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QSOS
--------------------------------------------------------

  ALTER TABLE "KYPOTA"."QSOS" ADD CONSTRAINT "QSO_FK" FOREIGN KEY ("LOG_ID")
	  REFERENCES "KYPOTA"."LOGS" ("LOG_ID") ENABLE;



--------------------------------------------------------
--  DDL for Sequence LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KYPOTA"."LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence QSO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KYPOTA"."QSO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;





REM INSERTING into KYPOTA.USERS
SET DEFINE OFF;
Insert into KYPOTA.USERS (USERNAME,PASSWORD,ENABLED,EMAIL) values ('user','$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a','Y','user@email.com');



REM INSERTING into KYPOTA.KYPARKS
SET DEFINE OFF;
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('BRL','Barren River Lake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('BBL','Big Bone Lick');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('BLB','Blue Licks Battlefield');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('BI','Breaks Interstate');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('BLR','Buckhorn Lake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('CC','Carr Creek');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('CCR','Carter Caves');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('CB','Columbus-Belmont');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('CF','Cumberland Falls');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('DH','Dale Hollow');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('DLR','Dawkins Line Rail trail');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('DTW','Dr. Thomas Walker');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('TS','Tom Sawyer');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('FB','Ft. Boonesborough');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('GB','General Butler');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('GL','Grayson Lake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('GRL','Green River Lake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('GLR','Greenbo Lake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('ISC','Isaac Shelby Cemetery');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('JD','Jefferson Davis');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('JW','Jenny Wiley');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('JJA','John James Audubon');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('KLR','Kenlake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('KDV','Kentucky Dam Village');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('KL','Kincaid Lake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('KC','Kingdon Come');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('LB','Lake Barkley');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('LCR','Lake Cumberland');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('LM','Lake Malone');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('LJW','Levi Jackson Wilderness');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('LH','Lincoln Homestead');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('MM','Mineral Mounds');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('MKH','My Old Kentucky Home');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('NB','Natural Bridge');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('NL','Nolin Lake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('OFH','Old Fort Harrod');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('OMM','Old Mulkey Meetinghouse');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('PL','Paintsville Lake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('PF','Pennyrile Forest');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('PB','Perryville Battlefield');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('PMR','Pine Mountain');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('PMT','Pine Mountain Scenic Trail');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('RRD','Rough River Dam');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('TL','Taylorsville Lake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('WSH','Waveland Historic Site');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('WH','White Hall Historic Site');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('WM','Wickliffe Mounds');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('WWH','William Whitley House');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('YL','Yatesville Lake');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('ALB','Abraham Lincoln Birthplace');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('BSF','Big South Fork');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('CN','Camp Nelson');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('CG','Cumberland Gap');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('FD','Fort Donelson');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('LAC','Lewis and Clark');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('MC','Mammoth Cave');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('TT','Trail of Tears');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('LBL','Land Between the Lakes');
Insert into KYPOTA.KYPARKS (ABBR,PARK_NAME) values ('GBI','General Burnside Island');
